# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 08:54
from __future__ import unicode_literals

import account.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nobp', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^(0[1-9]|1[1-9])(10{2}|00{2})([0-9][0-9])$')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('birth_date', models.DateField()),
                ('avatar', models.ImageField(blank=True, default='', upload_to=account.utils.user_directory_path)),
            ],
        ),
    ]
