# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 05:39
from __future__ import unicode_literals

import account.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nobp', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^(0[1-9]|1[1-9])(10{2}|00{2})([0-9][0-9])$')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('birth_date', models.DateField()),
                ('age', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('avatar', models.ImageField(blank=True, default='', upload_to=account.utils.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
