# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
